#' Overview tab module UI
#'
#' @param id Shiny module ID.
#' @export
mod_overview_ui <- function(id) {
  ns <- shiny::NS(id)
  bslib::page_fillable(
    bslib::layout_column_wrap(
      width = "200px",
      fill  = FALSE,
      bslib::value_box(
        title = bslib::tooltip(
          trigger = shiny::tagList(
            "Total Input Tokens ",
            bsicons::bs_icon("question-circle-fill", size = "0.75em")
          ),
          "Tokens sent to the model — every prompt, system message, and conversation history entry counts here.",
          placement = "bottom"
        ),
        value    = shiny::textOutput(ns("vb_input"),  inline = TRUE),
        theme    = "primary",
        showcase = bsicons::bs_icon("arrow-right-circle")
      ),
      bslib::value_box(
        title = bslib::tooltip(
          trigger = shiny::tagList(
            "Total Output Tokens ",
            bsicons::bs_icon("question-circle-fill", size = "0.75em")
          ),
          "Tokens generated by the model in responses. Output tokens are typically priced higher than input tokens.",
          placement = "bottom"
        ),
        value    = shiny::textOutput(ns("vb_output"), inline = TRUE),
        theme    = "success",
        showcase = bsicons::bs_icon("arrow-left-circle")
      ),
      bslib::value_box(
        title = bslib::tooltip(
          trigger = shiny::tagList(
            "Cache Tokens ",
            bsicons::bs_icon("question-circle-fill", size = "0.75em")
          ),
          "Sum of cache-write and cache-read tokens. Cache-read tokens are ~10x cheaper than standard input — large cache usage indicates efficient context reuse.",
          placement = "bottom"
        ),
        value    = shiny::textOutput(ns("vb_cache"),  inline = TRUE),
        theme    = "info",
        showcase = bsicons::bs_icon("lightning-charge")
      ),
      bslib::value_box(
        title = bslib::tooltip(
          trigger = shiny::tagList(
            "Est. Cost (USD) ",
            bsicons::bs_icon("question-circle-fill", size = "0.75em")
          ),
          "Estimated cost based on Anthropic's published per-token rates. See the Pricing tab for the exact rates used per model.",
          placement = "bottom"
        ),
        value    = shiny::textOutput(ns("vb_cost"),   inline = TRUE),
        theme    = "warning",
        showcase = bsicons::bs_icon("currency-dollar")
      ),
      bslib::value_box(
        title = bslib::tooltip(
          trigger = shiny::tagList(
            "API Requests ",
            bsicons::bs_icon("question-circle-fill", size = "0.75em")
          ),
          "Total number of individual API calls (rows) in the selected date range and filters.",
          placement = "bottom"
        ),
        value    = shiny::textOutput(ns("vb_reqs"),   inline = TRUE),
        theme    = "secondary",
        showcase = bsicons::bs_icon("send")
      )
    ),
    bslib::layout_columns(
      col_widths = c(3, 9),
      bslib::card(
        bslib::card_header("Filters"),
        shiny::dateRangeInput(
          ns("date_range"),
          label = bslib::tooltip(
            trigger = shiny::tagList(
              "Date range ",
              bsicons::bs_icon("question-circle-fill", size = "0.75em")
            ),
            "Limits all charts and totals to the selected window. Defaults to the past 90 days.",
            placement = "right"
          ),
          start = Sys.Date() - 90,
          end   = Sys.Date()
        ),
        shiny::selectInput(
          ns("filter_machine"),
          label = bslib::tooltip(
            trigger = shiny::tagList(
              "Machine ",
              bsicons::bs_icon("question-circle-fill", size = "0.75em")
            ),
            paste0(
              "The device or label where data originated. ",
              "‘api’ = fetched via an Admin API key. ",
              "‘manual’ = uploaded CSV (default label). ",
              "Custom labels come from the Machine label field on the Data tab."
            ),
            placement = "right"
          ),
          choices  = "All",
          selected = "All",
          multiple = TRUE
        ),
        shiny::selectInput(
          ns("filter_source"),
          label = bslib::tooltip(
            trigger = shiny::tagList(
              "Source ",
              bsicons::bs_icon("question-circle-fill", size = "0.75em")
            ),
            paste0(
              "Where usage records came from. ",
              "‘anthropic_api’ = fetched via Admin API key. ",
              "‘claude_code’ = local Claude Code session logs. ",
              "Other values come from the ‘source’ column in uploaded CSV files ",
              "(e.g. ‘console’ for Anthropic Console exports)."
            ),
            placement = "right"
          ),
          choices  = "All",
          selected = "All",
          multiple = TRUE
        ),
        shiny::selectInput(
          ns("stack_var"),
          label = bslib::tooltip(
            trigger = shiny::tagList(
              "Stack by ",
              bsicons::bs_icon("question-circle-fill", size = "0.75em")
            ),
            "Controls how the daily chart is colored and stacked. 'model' shows which Claude model was used; 'source' shows where the data came from; 'machine' compares across devices.",
            placement = "right"
          ),
          choices  = c("model", "source", "machine"),
          selected = "model"
        )
      ),
      bslib::card(
        full_screen = TRUE,
        bslib::card_header("Daily Token Usage"),
        shiny::plotOutput(ns("plot_daily"), height = "340px")
      )
    )
  )
}


#' Overview tab module server
#'
#' Owns filter state and computes the filtered reactive returned to the main
#' server for use by all other modules.
#'
#' @param id Shiny module ID.
#' @param raw_usage_rv `reactiveVal` holding the full usage tibble.
#' @return A reactive tibble of filtered usage data.
#' @export
mod_overview_server <- function(id, raw_usage_rv) {
  shiny::moduleServer(id, function(input, output, session) {
    logger::log_debug("mod_overview initialised", namespace = "shokenuse")

    shiny::observe({
      df <- raw_usage_rv()
      if (nrow(df) == 0) return()
      shiny::updateSelectInput(session, "filter_machine",
        choices  = c("All", sort(unique(df$machine))),
        selected = "All"
      )
      shiny::updateSelectInput(session, "filter_source",
        choices  = c("All", sort(unique(df$source))),
        selected = "All"
      )
    })

    filtered <- shiny::reactive({
      df <- raw_usage_rv()
      if (nrow(df) == 0) return(df)

      dr <- input$date_range
      if (!is.null(dr)) {
        df <- dplyr::filter(df, date >= dr[1], date <= dr[2])
      }

      fm <- input$filter_machine
      if (length(fm) > 0 && !("All" %in% fm)) {
        df <- dplyr::filter(df, machine %in% fm)
      }

      fs <- input$filter_source
      if (length(fs) > 0 && !("All" %in% fs)) {
        df <- dplyr::filter(df, source %in% fs)
      }

      df
    })

    totals <- shiny::reactive({
      df <- filtered()
      list(
        input  = sum(df$input_tokens,          na.rm = TRUE),
        output = sum(df$output_tokens,          na.rm = TRUE),
        cache  = sum(df$cache_creation_tokens + df$cache_read_tokens, na.rm = TRUE),
        cost   = if ("cost_usd" %in% names(df)) sum(df$cost_usd, na.rm = TRUE) else 0,
        reqs   = nrow(df)
      )
    })

    output$vb_input  <- shiny::renderText(
      scales::label_number(scale_cut = scales::cut_short_scale())(totals()$input))
    output$vb_output <- shiny::renderText(
      scales::label_number(scale_cut = scales::cut_short_scale())(totals()$output))
    output$vb_cache  <- shiny::renderText(
      scales::label_number(scale_cut = scales::cut_short_scale())(totals()$cache))
    output$vb_cost   <- shiny::renderText(
      scales::dollar(totals()$cost, accuracy = 0.01))
    output$vb_reqs   <- shiny::renderText(
      scales::comma(totals()$reqs))

    output$plot_daily <- shiny::renderPlot({
      df <- filtered()
      if (nrow(df) == 0) return(.empty_plot("No data in selected range"))

      stack_col <- input$stack_var %||% "model"

      daily <- df |>
        dplyr::group_by(date, .data[[stack_col]]) |>
        dplyr::summarise(
          tokens = sum(input_tokens + output_tokens +
                         cache_creation_tokens + cache_read_tokens,
                       na.rm = TRUE),
          .groups = "drop"
        )

      ggplot2::ggplot(
        daily,
        ggplot2::aes(x = date, y = tokens, fill = .data[[stack_col]])
      ) +
        ggplot2::geom_col() +
        ggplot2::scale_y_continuous(
          labels = scales::label_number(scale_cut = scales::cut_short_scale())
        ) +
        ggplot2::scale_x_date(date_breaks = "1 week", date_labels = "%b %d") +
        ggplot2::labs(x = NULL, y = "Tokens", fill = stack_col) +
        ggplot2::theme_minimal(base_size = 13) +
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 30, hjust = 1))
    }, res = 96)

    filtered
  })
}
